FROM arm64v8/ros:humble-perception-jammy as base

# Setup basic
RUN apt update && apt install -y \
    git \
    gcc \
    curl \
    wget \
    python3-pip \
    libudev-dev \
    libgtk2.0-dev \
    libcanberra-gtk-module \
    libcanberra-gtk3-module && \
    pip3 install flask waitress opencv-python numpy datetime

WORKDIR /opt/aether

COPY src/sample.py /opt/aether/sample.py
